import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { getCssText } from '../../stitches.config'
import { globalStyles } from '@/styles/global'

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-nunito',
})

export const metadata: Metadata = {
  title: 'Book Wise | Home Page',
  description: 'Generated by create next app',
}

globalStyles()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{
            __html: getCssText(),
          }}
        />
      </head>
      <body className={nunito.className}>{children}</body>
    </html>
  )
}
